In [1]:
import pandas as pd

df = pd.read_csv(r'//Users/gavin/Documents/Metis/Coursework/Week_1/Project_1/reference_data/coords_fix.csv')
df.head(15)

,Station,Lat,Long,Women,Professional,Income,Transport,Volume
0,125th St,40.804428,-73.937449,red,darkred,darkred,lightgreen,64645.129870
1,14th St-Union Square,40.735066,-73.990416,lightgreen,gold,orange,gold,90099.840909
2,23rd St,40.743942,-73.995605,red,green,gold,green,83747.983766
3,34th St-Herald Square,40.749834,-73.988080,lightgreen,lightgreen,orange,darkred,98827.532468
4,34th St-Penn Station,40.750997,-73.990805,darkred,gold,green,red,140104.298701
5,Port author - 42nd St,40.757483,-73.989454,darkred,darkred,red,red,80674.639610
6,59th St,40.762397,-73.968321,orange,green,green,darkred,56919.165584
7,59th St-Columbus C,40.768247,-73.981929,lightgreen,gold,lightgreen,red,60960.480519
8,86th St,40.779492,-73.955589,gold,red,orange,green,76594.987013
9,96th St,40.785804,-73.950912,gold,gold,orange,green,56492.883117
10,Canal St,40.718574,-74.000560,gold,orange,lightgreen,gold,63026.181818
11,Flushing-Main St,40.759600,-73.830030,green,darkred,darkred,orange,52277.983766
12,Fulton St,40.710459,-74.009326,green,lightgreen,gold,gold,77993.344156
13,Grand Central-42nd,40.752476,-73.978137,orange,lightgreen,gold,darkred,121782.597403
14,Times Square-42nd,40.755315,-73.986826,darkred,red,Red,orange,87716.357143

In [2]:

large=df['Volume'].max()
small=df['Volume'].min()

rad=5

In [3]:
import folium


folium_map = folium.Map(location=[40.738, -73.98],
                        zoom_start=11,
                        tiles="CartoDB positron")
folium_map.save('new_york.html')

In [4]:
#women

for index, row in df.iterrows():
    long =row['Long']
    lat =row['Lat']
    color = row['Women']
    popup_text = """{}"""
    popup_text = popup_text.format(row['Station'])
    marker = folium.CircleMarker(location = [lat, long], radius=rad*(row['Volume']/small), color=color, fill=True, popup=popup_text)
    
    marker.add_to(folium_map)
    
folium_map.save('new_york_women.html')

In [5]:
#professional

for index, row in df.iterrows():
    long =row['Long']
    lat =row['Lat']
    color = row['Professional']
    popup_text = """{}"""
    popup_text = popup_text.format(row['Station'])
    marker = folium.CircleMarker(location = [lat, long], radius=rad*(row['Volume']/small), color=color, fill=True, popup=popup_text)
    marker.add_to(folium_map)
    
folium_map.save('new_york_professional.html')

In [6]:
#income

for index, row in df.iterrows():
    long =row['Long']
    lat =row['Lat']
    color=row['Income']
    popup_text = """{}"""
    popup_text = popup_text.format(row['Station'])
    marker = folium.CircleMarker(location = [lat, long], radius=rad*(row['Volume']/small), color=color, fill=True, popup=popup_text)
    
    marker.add_to(folium_map)
    
folium_map.save('new_york_income.html')

In [7]:
#transport

for index, row in df.iterrows():
    long =row['Long']
    lat =row['Lat']
    color=row['Transport']
    popup_text = """{}"""
    popup_text = popup_text.format(row['Station'])
    marker = folium.CircleMarker(location = [lat, long], radius=rad*(row['Volume']/small), color=color, fill=True, popup=popup_text)
    
    marker.add_to(folium_map)
    
folium_map.save('new_york_transport.html')

In [9]:
# Volume

for index, row in df.iterrows():
    long =row['Long']
    lat =row['Lat']
    color='blue'
    popup_text = """{}"""
    popup_text = popup_text.format(row['Station'])
    marker = folium.CircleMarker(location = [lat, long], radius=rad*(row['Volume']/small), color=color, fill=True, popup=popup_text)
    
    marker.add_to(folium_map)
    
folium_map.save('new_york_volume.html')